# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sb_3_gui.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(962, 702)
        MainWindow.setStyleSheet("QPushButton {border : 1px solid black; background : white; color : rgb(2,1,53); border-radius : 30px}\n"
"QPushButton:hover {background : rgb(228, 255, 255);}\n"
"QPushButton:disabled {background : rgb(216, 216, 216)}\n"
"\n"
"dragDropButton {color : rgb(2, 1, 53); background : white; border : 2px dashed rgb(2, 1, 53); min-height : 71px; min-width : 71px; max-height : 71px; max-width : 71px; border-radius : 0px;}\n"
"dragDropButton:hover {color : white; background : rgb(2, 1, 53); border : 2px dashed white;}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(30, 8, 320, 365))
        self.groupBox.setObjectName("groupBox")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox.setGeometry(QtCore.QRect(10, 20, 92, 24))
        self.checkBox.setChecked(False)
        self.checkBox.setObjectName("checkBox")
        self.spinBox = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox.setEnabled(False)
        self.spinBox.setGeometry(QtCore.QRect(120, 20, 48, 24))
        self.spinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(10)
        self.spinBox.setObjectName("spinBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(170, 20, 41, 24))
        self.label.setObjectName("label")
        self.spinBox_2 = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_2.setEnabled(False)
        self.spinBox_2.setGeometry(QtCore.QRect(220, 20, 48, 24))
        self.spinBox_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_2.setMinimum(1)
        self.spinBox_2.setMaximum(10)
        self.spinBox_2.setObjectName("spinBox_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(270, 20, 48, 24))
        self.label_2.setObjectName("label_2")
        self.library = Workout(self.groupBox)
        self.library.setGeometry(QtCore.QRect(9, 50, 302, 302))
        self.library.setAcceptDrops(False)
        self.library.setObjectName("library")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 300, 300))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.library.setWidget(self.scrollAreaWidgetContents)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(30, 380, 320, 111))
        self.groupBox_4.setObjectName("groupBox_4")
        self.spinBox_3 = QtWidgets.QSpinBox(self.groupBox_4)
        self.spinBox_3.setGeometry(QtCore.QRect(10, 20, 48, 24))
        self.spinBox_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_3.setMinimum(1)
        self.spinBox_3.setMaximum(5)
        self.spinBox_3.setObjectName("spinBox_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label_4.setGeometry(QtCore.QRect(60, 20, 121, 24))
        self.label_4.setObjectName("label_4")
        self.spinBox_4 = QtWidgets.QSpinBox(self.groupBox_4)
        self.spinBox_4.setGeometry(QtCore.QRect(10, 50, 48, 24))
        self.spinBox_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_4.setMinimum(4)
        self.spinBox_4.setMaximum(20)
        self.spinBox_4.setObjectName("spinBox_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_4)
        self.label_5.setGeometry(QtCore.QRect(60, 50, 131, 24))
        self.label_5.setObjectName("label_5")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox.setGeometry(QtCore.QRect(60, 80, 251, 26))
        self.comboBox.setStyleSheet("")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_6 = QtWidgets.QLabel(self.groupBox_4)
        self.label_6.setGeometry(QtCore.QRect(10, 80, 51, 24))
        self.label_6.setObjectName("label_6")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(30, 500, 215, 61))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setEnabled(False)
        self.pushButton_5.setGeometry(QtCore.QRect(245, 500, 105, 61))
        self.pushButton_5.setObjectName("pushButton_5")
        self.workout = Workout(self.centralwidget)
        self.workout.setGeometry(QtCore.QRect(30, 575, 827, 77))
        self.workout.setAcceptDrops(True)
        self.workout.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.workout.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.workout.setObjectName("workout")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 900, 75))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.workout.setWidget(self.scrollAreaWidgetContents_2)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(360, 30, 571, 481))
        self.widget.setObjectName("widget")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(870, 585, 60, 61))
        self.label_3.setStyleSheet("QLabel {font-size:48pt; color:rgb(2,1,59);}\n"
"")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 962, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAdd_Speed_Event = QtWidgets.QAction(MainWindow)
        self.actionAdd_Speed_Event.setObjectName("actionAdd_Speed_Event")
        self.actionManage_Events = QtWidgets.QAction(MainWindow)
        self.actionManage_Events.setObjectName("actionManage_Events")
        self.actionCurrent_Next_Events = QtWidgets.QAction(MainWindow)
        self.actionCurrent_Next_Events.setObjectName("actionCurrent_Next_Events")
        self.actionTimer = QtWidgets.QAction(MainWindow)
        self.actionTimer.setObjectName("actionTimer")
        self.actionClicker = QtWidgets.QAction(MainWindow)
        self.actionClicker.setObjectName("actionClicker")
        self.menuFile.addAction(self.actionAdd_Speed_Event)
        self.menuFile.addAction(self.actionManage_Events)
        self.menuView.addAction(self.actionCurrent_Next_Events)
        self.menuView.addAction(self.actionTimer)
        self.menuView.addAction(self.actionClicker)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(MainWindow)
        self.checkBox.stateChanged['int'].connect(self.spinBox.setValue)
        self.checkBox.toggled['bool'].connect(self.spinBox.setEnabled)
        self.checkBox.toggled['bool'].connect(self.spinBox_2.setEnabled)
        self.checkBox.stateChanged['int'].connect(self.spinBox_2.setValue)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Speed Bot"))
        self.groupBox.setTitle(_translate("MainWindow", "Add Event"))
        self.checkBox.setText(_translate("MainWindow", "alternating"))
        self.label.setText(_translate("MainWindow", "reps in"))
        self.label_2.setText(_translate("MainWindow", "groups"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Workout Settings"))
        self.label_4.setText(_translate("MainWindow", "full workout reps"))
        self.label_5.setText(_translate("MainWindow", "second rest warning"))
        self.comboBox.setItemText(0, _translate("MainWindow", "current/next events"))
        self.comboBox.setItemText(1, _translate("MainWindow", "time"))
        self.comboBox.setItemText(2, _translate("MainWindow", "clicker"))
        self.label_6.setText(_translate("MainWindow", "display"))
        self.pushButton_4.setText(_translate("MainWindow", "RUN"))
        self.pushButton_5.setText(_translate("MainWindow", "STOP"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.actionAdd_Speed_Event.setText(_translate("MainWindow", "Add Speed Event..."))
        self.actionManage_Events.setText(_translate("MainWindow", "Manage Events..."))
        self.actionCurrent_Next_Events.setText(_translate("MainWindow", "Current/Next Events"))
        self.actionTimer.setText(_translate("MainWindow", "Timer"))
        self.actionClicker.setText(_translate("MainWindow", "Clicker"))


from jump_classes import Workout
